ajout stucture Guide installation + creation fichier scriptAD
HEIGVD-PRO-A-07/HEIGVD-PRO-A-07-Documentation pull request #19
Opened 2020-05-22 13:02 UTC by dosseggegw1

2020-05-24 12:54 UTC, g-roch requested changes

2020-05-24 12:54 UTC, g-roch commented on manuelInstallation/ListUsers.csv
> +Laurent;Thoeny;laurent.t;CN=Users,DC=PRO,DC=local;Password1$;Eleves
Très bien de séparer les users du scripts, mais ne faudrait-il pas aussi avoir un prof ?

2020-05-24 12:54 UTC, g-roch commented on manuelInstallation/README.md
> +``.\PRO.ex [server|professeur|eleve] <ipServer> <Port>``
C'est pour le serveur `.\PRO.exe server <port>`
et pour le prof et l'élève `.\PRO.exe client <ipserver> <port>`

2020-05-24 12:54 UTC, g-roch commented on manuelInstallation/README.md
> +//Serveur
Indiquer comment faire pour configurer le sid des groupes élève et prof

2020-05-24 13:42 UTC, dosseggegw1 commented on manuelInstallation/ListUsers.csv
> +Laurent;Thoeny;laurent.t;CN=Users,DC=PRO,DC=local;Password1$;Eleves
Il suffit juste de changer le groupe Eleves par Professeurs. Mais yes, je push une version où il y a au moins un prof ;)

2020-05-24 15:13 UTC, g-roch commented on manuelInstallation/ListUsers.csv
> +Laurent;Thoeny;laurent.t;CN=Users,DC=PRO,DC=local;Password1$;Eleves
Merci

2020-05-26 12:53 UTC, CassandreWoj approved these changes

2020-05-26 12:57 UTC, g-roch approved these changes

2020-05-26 12:58 UTC, merged